<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Asynchronous JavaScript</title>
</head>
<body>
    <h1>Asynchronous JavaScript</h1>
    <script>

    	/*const second = () => {
    		setTimeout(() => {
    			console.log('Async, Hey there!');
    		}, 2000);
    	}


        const first = () => {
        	console.log('Hey there!');
        	second();
        	console.log('the end!');
        }

        first();*/


// The following is an example of the so called 'callback hell', which is a callback inside a callback inside a callback and so on.
        /*function getRecipe() {

        	setTimeout(() => {

        		const recipeID = [45, 346, 23, 56];
        		console.log(recipeID);

        		setTimeout((id) => {

        			const recipe = {title: 'Fresh tomato pasta', publisher: 'Telis'};
        			console.log(`${id}: ${recipe.title}`);

        			setTimeout(publisher => {
        				const recipe = {title: 'Italian Pizza', publisher: 'Telis'};
        				console.log(recipe);

        			}, 1500, recipe.publisher);

        		}, 1500, recipeID[2]);

        	}, 1500);

        }
        getRecipe();*/

        //recreating the part from the code above, where we get the ids from the server(fake ajax call)
        //the executor function gets two arguements, the callback functions resolve and reject. Its because it is used to inform the promise if the event it is handling was successful or not. In this case we dont have to use the reject function.


    // Producing promises
        const getIDs = new Promise((resolve, reject) => {
        	setTimeout(() => {
        		resolve([45, 346, 23, 56]);
        	}, 1500);

        });

        const getRecipe = recID => {
        	return new Promise((resolve, reject) => {
        		setTimeout(ID => {
        			const recipe = {title: 'Fresh tomato pasta', publisher: 'Telis'};
        			resolve(`${ID}: ${recipe.title}`);

        		}, 1500, recID);
        		
        	});
        };

        const getRelated = publisher => {
        	return new Promise((resolve, reject) => {
        		setTimeout(pub => {
        			const recipe = {title: 'Italian Pizza', publisher: 'Telis'};
        			resolve(`${pub}: ${recipe.title}`);
        		}, 1500, publisher);

        	});

        };

    // Consuming promises    

        /*getIDs.then(IDs => {
        	console.log(IDs);
        });*/

/*        getIDs
        .then(IDs => {
        	console.log(IDs);
        	return getRecipe(IDs[2]);
        })
        .then(recipe => {
        	console.log(recipe);
        	return getRelated('Telis Nikolaou');
        })
        .then(recipe => {
        	console.log(recipe);
        })

        .catch(error => {
        	console.log(error);
        });*/

// New way of consuming promises introduced in the ES8, or ES2017 ( async await)
// await can only be used inside an async function. Await stops the function until promise is consumed, but it doesnt matter because async function already
// runs in the background(asynchronously)

       /* async function getRecipesAW() {
        	const IDs = await getIDs;
        	console.log(IDs);
        	const recipe = await getRecipe(IDs[2]);
        	console.log(recipe);
        	const related = await getRelated('Telis Nikolaou');
        	console.log(related);


        }
        getRecipesAW(); // this code runs synchronously*/


        // the following will not return the recipe because the console.log(rec) below is ran way before the promise is resolved
         /* async function getRecipesAW() {
        	const IDs = await getIDs;
        	console.log(IDs);
        	const recipe = await getRecipe(IDs[2]);
        	console.log(recipe);
        	const related = await getRelated('Telis Nikolaou');
        	console.log(related);

        	return recipe;

        }
        const rec = getRecipesAW(); // this code runs synchronously
        console.log(rec);
*/


		// We can do this instead

		/*async function getRecipesAW() {
        	const IDs = await getIDs;
        	console.log(IDs);
        	const recipe = await getRecipe(IDs[2]);
        	console.log(recipe);
        	const related = await getRelated('Telis Nikolaou');
        	console.log(related);

        	return recipe;

        }
        getRecipesAW().then(result => console.log(`${result} is the best ever!`)); // this code runs synchronously
*/


		
		// we prefixed the crossorigin (changeed to cors-anywhere) url in order to fix the cross origin problem. Normally we would channel the request from our server, where cross origin policy doesnt exist.
		// fetch returns a promise, se we just have to consume it. (the good thing about using 3rd party apis)
		function getWeather(woeid) {   //woeid means where on earth id

		fetch(`https://cors-anywhere.herokuapp.com/https://www.metaweather.com/api/location/${woeid}/`)

		.then(result => {
			console.log(result);
			return result.json(); // returns a promise
		})
		.then(data => {
			//console.log(data);
			const today = data.consolidated_weather[0];
			console.log(`Temperatures in ${data.title} are between ${today.min_temp} and ${today.max_temp}.`);
		})
		.catch(error => console.log(error));

	}

	getWeather(2487956); // id for San Francisco
	getWeather(44418); // id for London
	



    </script>
</body>
</html>